### ISSUE TITLE
WARNING: The `gcloud ml-engine` commands have been renamed and will soon be removed. Please use `gcloud ai-platform` instead.

### ISSUE THREAD

**Issue by victusfate** [GoogleCloudPlatform/tensorflow-recommendation-wals#10]
found this example is legacy but there are no current similar examples using ai-platform

**Comment by victusfate** [comment]
related issue https://github.com/GoogleCloudPlatform/cloudml-samples/issues/452#issuecomment-525483183

**Comment by victusfate** [comment]
closing this out

**Comment by MaanasPeri23** [comment]
> related issue [GoogleCloudPlatform/cloudml-samples#452 (comment)](https://github.com/GoogleCloudPlatform/cloudml-samples/issues/452#issuecomment-525483183)

Hey, I checked out the related issue but was still unable to find the proper commands for this problem. Would you mind following up with me on your solution? 

Thanks!
